Repository LycheeOrg/Lychee-front, pull requests merged in 2022-09, with the labels that each got.

#310 Add user and better structure to session json
  scripts/3rd-party/backend.js
  scripts/main/album.js
  scripts/main/contextMenu.js
  scripts/main/header.js
  scripts/main/lychee.js
  scripts/main/multiselect.js
  scripts/main/settings.js
  scripts/main/view.js
Labels: Merge Ready

#308 support multiple paths, space separated
  scripts/main/lychee_locale.js
  scripts/main/upload.js
Labels: Merge Ready

#321 Replace escaped spaces
  scripts/main/upload.js
Labels: bug, High Priority

#324 Don't interpret logs as HTML
  scripts/main/view.js
Labels: bug, High Priority, Security

#325 Fix most ecaping of user provided input
  scripts/main/album.js
  scripts/main/build.js
  scripts/main/photo.js
  scripts/main/sidebar.js
  scripts/main/view.js
Labels: bug, High Priority, Security

#326 Limit HTML escaping to album description
  scripts/main/build.js
Labels: High Priority
